version: '3.1'

services:
  user:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
      target: development
    # 커맨드는 compose의 커맨드로 오버라이드 됨
    command: pnpm run start:dev user
    # postgres를 의존한다
    depends_on:
      postgres_user:
        condition: service_healthy

    env_file:
      - ./apps/user/.env

    # '현재 컴퓨터 포트:컨테이너 안 포트'
    ports:
      - '3001:3000'
    # 동기화
    volumes:
      - .:/usr/src/app
      # 연동을 하지 않는다
      - /usr/src/app/node_modules
    environment:
      - WATCHPACK_POLLING=true

  postgres_user:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '6001:5432'
    volumes:
      - ./postgres/user:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  product:
    build:
      context: .
      dockerfile: ./apps/product/Dockerfile
      target: development
    command: pnpm run start:dev product
    depends_on:
      postgres_product:
        condition: service_healthy
    env_file:
      - ./apps/product/.env
    ports:
      - '3002:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - WATCHPACK_POLLING=true

  postgres_product:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '6002:5432'
    volumes:
      - ./postgres/product:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
